### ISSUE TITLE
knockd new tag

### ISSUE THREAD

**Issue by Oekn5w** [Oekn5w/dummy#1]
@TDFKAOlli

forgive me to write to you this way, but issues are disabled in your knockd fork.
Could you please add a tag to the newest commit on your knockd fork, maybe something like 0.8.1 or 0.9 ?
I'm trying to get this integrated into the Alpine 3.12 repo (they are already using your 0.8 tag). The tag contains a bug, when using the utility without IPv6 (either via no address assigned or the -4 argument) which has been fixed in the meantime. As I'm using the utility in docker, IPv6 is disabled by default, therefore throwing an error in alpine based containers (specifically in some branches of https://github.com/itzg/docker-minecraft-server )

Thanks

**Comment by TDFKAOlli** [comment]
@Oekn5w No problem. I pushed the new tag 0.8.1 on the knock repo fork. Hope it helps!
I just wonder why issues are disabled on my fork... Have to check where to enable them. 😄   ... found it and enabled it 😏

**Comment by Oekn5w** [comment]
@TDFKAOlli Thank you. If you want to follow the upstream conversation: https://gitlab.alpinelinux.org/alpine/aports/-/issues/11092
